cam_model: Pinhole
cam_width: 760
cam_height: 1008
scale: 1.0
cam_fx: 1190.2300636172322
cam_fy: 1189.834025238654
cam_cx: 1453.4137726192234
cam_cy: 1991.589305493047
cam_d0: -0.009468151762882921
cam_d1: -0.004500166054282193
cam_d2: 0.0017771166601528402
cam_d3: -0.0009476961813220143