cam_model: Pinhole
cam_width: 3040
cam_height: 4032
scale: 0.5
cam_fx: 1190.2300
cam_fy: 1189.8340
cam_cx: 1453.4137
cam_cy: 1991.5893
cam_d0: -0.009468151762882921
cam_d1: -0.004500166054282193
cam_d2: 0.0017771166601528402
cam_d3: -0.0009476961813220143